# Generated by Django 2.0.2 on 2018-06-02 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.URLField(blank=True, default='http://owgxfd8jv.bkt.clouddn.com/HollowRock.jpg', verbose_name='封面图片'),
        ),
    ]
