# Generated by Django 2.0.2 on 2018-06-04 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180603_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='image',
        ),
        migrations.RemoveField(
            model_name='link',
            name='qrcode',
        ),
    ]
