# Generated by Django 2.0.6 on 2018-06-05 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180604_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.TextField(
                blank=True, default='', verbose_name='内容'),
        ),
    ]
