# Generated by Django 2.0.6 on 2018-06-06 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20180606_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.FileField(upload_to='blog/uploads/'),
        ),
    ]
