# Generated by Django 2.0.6 on 2018-06-28 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20180607_0858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='article',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='pid',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
