# Generated by Django 2.0.6 on 2018-07-01 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='reply_name',
            field=models.CharField(max_length=100, null=True, verbose_name='回复谁'),
        ),
    ]
