# Generated by Django 2.0.6 on 2018-07-01 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_auto_20180701_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user_email',
            field=models.EmailField(blank=True, help_text='邮箱地址，用于发送回复', max_length=50, null=True, verbose_name='邮箱地址'),
        ),
    ]
